### PR TITLE
vuepress

### PR DESCRIPTION
**Pull request by clarkeash**
Hey @ssx, I have added the docs for one of my rules for now, we can add the other rules once we are happy with everything else  😄

### CODE REVIEW

**Comment by clarkeash** [comment]
Do you want to host this on github pages (will have to commit the (build/dist) directory. Alternatively it could be hosted on something like netlify, but then we'd probably want a domain 🤷‍♂️

**Comment by ssx** [comment]
We'll go for pages for now, domain is on the cards. I'll support the costs with @issetio.

**Comment by ssx** [comment]
@clarkeash ping the assets/dist up with this, I'll sort the domain out next month and we'll just get this launched on Github pages.

**Comment by clarkeash** [comment]
@ssx sure, I was gonna port more docs over, but been busy

**Comment by clarkeash** [comment]
dist: `.vuepress/dist`

**Pull request merged**
