### PR TITLE
Added a "Start Validating" button to the first section

### PR DESCRIPTION
**Pull request by tylercd100**
Added a "Start Validating" button to the first section so people can find the repos and start using them. Currently links to [here](https://github.com/laravel-validation-rules/readme)

image

### CODE REVIEW

**Comment by clarkeash** [comment]
wouldn't linking to https://laravel-validation-rules.github.io/contributing.html be a better option?

**Comment by clarkeash** [comment]
I get what you are trying to achieve but it seems strange to link to the readme which then links back to where you just came from.

**Comment by tylercd100** [comment]
The problem with the homepage is that there is no way to "get started." 
How do I install LVR? My only option is to contribute?

**Comment by tylercd100** [comment]
The readme contains links to all the validators

**Comment by ssx** [comment]
I think it makes sense to split out the getting started into two blocks, one for using and one for contributions 🙂

I’ll have time this weekend to tidy up the site a little.

**Pull request merged**
